-- SCRIPT DE MIGRAÇÃO SEGURA PARA NEON (USAR NO CONSOLE)
-- Este script adiciona apenas o que falta, sem apagar seus 113 clientes.

-- 1. ADICIONAR COLUNAS FALTANTES NA TABELA DE CLIENTES
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cnpj TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS nome_fantasia TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS porte TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS data_abertura TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cnae_principal TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cnae_secundario TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS natureza_juridica TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS logradouro TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS numero TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS complemento TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS bairro TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS municipio TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS uf TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS telefone TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS situacao_cadastral TEXT DEFAULT 'ATIVA';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS data_situacao_cadastral TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS motivo_situacao TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS codigo_erp TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS frequencia_compra TEXT;

-- 2. ADICIONAR COLUNAS FALTANTES NO KANBAN (PROJETOS E VISITAS)
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS contact_name TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS contact_role TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS value DECIMAL(12,2);
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS temperature TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS visit_date DATE;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS visit_time TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS visit_type TEXT;
ALTER TABLE kanban_items ADD COLUMN IF NOT EXISTS observations TEXT;

-- 3. ADICIONAR COLUNAS FALTANTES NO FATURAMENTO (SE NECESSÁRIO)
ALTER TABLE billings ADD COLUMN IF NOT EXISTS erp TEXT;
ALTER TABLE billings ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'FATURADO';

-- 4. TABELA DE METAS (ESTRATÉGICO)
CREATE TABLE IF NOT EXISTS monthly_goals (
    period TEXT PRIMARY KEY,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
